emilk/eframe_template

README.md, build_web.sh
Use [`cargo metadata`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) to get the actual `target` directory and `jq` to extract directory from returned JSON.
https://packages.fedoraproject.org/pkgs/jq/ tells that Fedora package is named `jq` but I haven't check that, I have only Ubuntu.
=> Correctly determine the target directory when project inside workspace

build_web.sh
- Quotes all shell variables to avoid expansion/wordsplitting (in the unlikely case a folder is named something like `ab*c` or `a -rf * bc`)
- Use `[[` consistently. Shell is already specified as bash, so this should be fine
- Use `$()` over ``
=> Use shell best practices in build_web.sh

src/main.rs
This hides the console window on Windows, its only enabled on release builds as you lose stdout when using it.
=> Hide console window in release builds on Windows

README.md
`README.md` was missing a line for `main.rs` instructions and the code block syntax had an extra blank space before the specified language
=> docs: Add template rename instruction in `main.rs` & removed extra space

Cargo.toml, README.md
Linked to #48 : it is simpler and more logical to rename binary than rename library 😉
=> 🚨 Fix compilation warning about bin name conflict.

build_web.bat
Closes emilk/eframe_template#56
=> 🐛 Fix path containing spaces in `build_web.bat`

docs/index.html
Closes #67
Remove the top-level path (`/`) from all source links in index.html so that
the template takes relative paths can work when hosted under a path,
e.g. `https://emilk.github.io/eframe_template/`
=> Make paths in index.html relative

README.md
Add fontconfig-devel installation on Fedora to README.md
=> Update README.md to compile on Fedora

.cargo/config.toml, README.md
Trunk hooks is not enough to set env vars, so we need to use this workaround for now. 
fortunately, rustc doesn't complain about random cfg flags which are not used, so this doesn't affect  desktop fortunately.
=> add rust flags in cargo config for web-sys unstable

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/main.rs
had to run cargo update to resolve a dependency issue when building with wgpu, keeping those changes here
=> Update to egui/eframe 0.20.0

.cargo/config.toml
This makes sure that rust analyzer and cargo build (by extension trunk) don't invalidate build cache.
=> fixes #93 . use target, instead of build section for web unstable apis

Trunk.toml
By default, Trunk uses infinite caching. Without a file hash, this makes it quite easy for users to see stale copies of an application. The file hash (Trunk's default setting) ensures that users always load the exact hashed version that corresponds to what is currently deployed.
See also: https://github.com/thedodd/trunk/blob/master/Trunk.toml#L12-L13
Let me just add: I'm not sure why the setting was added in the first place, because the `Trunk.toml` contained no comments. But I've been wondering why Trunk has such a horrible caching policy for several months without realizing that eframe_template was setting an (arguably bad) non-default setting here.
=> Remove filehash setting from Trunk.toml

src/main.rs
Make it easier for new user to figure out how to set the icon for native apps. Would have liked to have used the same one as the web version but the favion is an ico file so used one of the other files I found in the assets folder. Not sure if I picked the most suitable one or if there was a way to do the same thing with an ico file.
=> Provide starter code to set native icon

README.md
For a little bit I was wondering why my deployment wasn't working, even though I changed very little. What happened was I deleted the `.git` folder and re-initialized the repository to clear commit history, but my default initial branch name is `main`. That broke the workflow because the `pages.yml` file by default uses the `master` branch
```yml
on:
push:
branches:
- master
```
So this PR just adds a note in the README
I think it might also be worth considering adding a couple common branch names in the `pages.yml` file and have the user uncomment them (my eyes skipped over `master` since it looks similar to `main`)
```yml
on:
push:
branches:
- master
```
=> Add note for Github Pages when initial branch is not named master

.github/workflows/pages.yml
This PR fixes the workflow for the page deployment using a modified public URL, as discussed in #116. This should also fix the issue that the template app is currently not loading properly.
=> Fix workflow file for page deploy

src/app.rs
The name of the primary branch in the upstream Repo is master not main. This PR fixes the link. Alternatively the name of the primary branch could just be changed to main as well.
=> Fix link to eframe

flake.nix
This will make it far easier to get started with eframe/egui. Simply running the following command will (hopefully) set up a working environment: `nix --experimental-features 'nix-command flakes' develop` (if Nix is installed)
=> Add a `flake.nix`

index.html
Proof:
```
git clone https://github.com/emilk/eframe_template.git && lychee .
```
```
31/31 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links                                                                                              Issues found in 1 input. Find details below.
[./eframe_template/index.html]:
✗ [ERR] file:///tmp/tmp.xuDXKdo4H8/eframe_template/icon_ios_touch_192.png | Failed: Cannot find file
✗ [ERR] file:///tmp/tmp.xuDXKdo4H8/eframe_template/manifest.json | Failed: Cannot find file
🔍 31 Total (in 0s) ✅ 29 OK 🚫 2 Errors
```
change links to these assets
- https://github.com/emilk/eframe_template/pull/137
- related to https://github.com/rerun-io/ewebsock/pull/38#issuecomment-2150380393
=> Fix `index.html` links to `manifest` and `apple-touch-icon`

.github/workflows/pages.yml
The current pages actions produce a lot of deprecation warnings from github. This should fix that.
`actions-rs` is also archived and unmaintained. The configuration here is simple enough to just throw in the commands directly so it's probably a good idea to do that.
=> Update pages action to avoid deprecation issues

.github/workflows/rust.yml
At the moment, it appears that musl targets are not working: https://github.com/rust-windowing/winit/issues/1818
To use gnu, it's necessary to use glib 2.27, for that, cross need to be installed manually from development branch: https://github.com/cross-rs/cross/issues/1510
=> Update CI deployment

index.html
Fix https://github.com/emilk/eframe_template/pull/142#issuecomment-2229172436
Note that only 
```
<link rel="manifest" href="assets/manifest.json">
<link rel="apple-touch-icon" href="assets/icon_ios_touch_192.png">
```
are really used in the final `index.html`
=> Fix assets

Cargo.toml
This allows `eframe_template` to compile when switching from `glow` to `wgpu` backend.
Fixes #158.
=> Pin web-sys dependency to < 0.3.70.

Cargo.lock, Cargo.toml
This PR builds upon #159 and updates a few dependencies in `Cargo.lock` so that `eframe_template` can be compiled with the `wgpu` backend *without* removing and regenerating `Cargo.lock` from scratch.
Before this change, the following compile error occurs after switching from `glow` to `wgpu` backend:
```
ben@Bens-MacBook-Pro eframe_template % cargo check
error: failed to select a version for `termcolor`.
... required by package `naga v0.20.0`
... which satisfies dependency `naga = "^0.20.0"` of package `wgpu v0.20.1`
... which satisfies dependency `wgpu = "^0.20.0"` of package `eframe v0.28.0`
... which satisfies dependency `eframe = "^0.28"` (locked to 0.28.0) of package `eframe_template v0.1.0 (/Users/ben/Documents/Fractals/eframe_template)`
versions that meet the requirements `^1.4.1` …
```
=> Update `Cargo.lock` to allow compiling with `wgpu` backend

flake.nix
I was trying to set up an eframe project and the nix flake was not working. It worked after I fixed the package name like this.
=> fixed pkg-config package name in flake.nix

Trunk.toml, assets/manifest.json, index.html
I noticed that  app shell isn't correctly cached by the service worker. Consequently PWA doesn't start correctly.
**Steps to reproduce**
- Build and serve the app: `trunk serve`
- Open app in the browser (chromium)
- Click "Install egui Template PWA"
- Close PWA
- Stop the server (trunk)
- Start previously installed PWA
**Proposed solution**
1. trunkrs adds hashes to the file names: `eframe_template-*`. This makes paths in `sw.js` under `filesToCache` invalid. I solved it by adding `filehash = false`. The other option could be generating `sw.js` with correct filenames in `post_build` hook of trunkrs.
2. I noticed that when `manifest.json` is served from `assets/`, then installed PWA starts from attempting to read `assets/index.html` from cache. The file is non-existing, so startup fails. …
=> fix PWA asset paths

Cargo.toml
I wasn't sure if this feature was left out intentionally but realized that it is actually one of the [default features](https://github.com/emilk/egui/blob/a2afc8d092a4e3f0b17675b114db8fad08810947/crates/eframe/Cargo.toml#L41) so created this PR to add it as I suspect it was an oversight rather than a conscious decision.
=> fix: restore missing x11 default feature

.github/workflows/rust.yml
* Reverts emilk/eframe_template#139
This is required to unblock updating to Rust 1.85, which is required by the upcoming egui release:
* https://github.com/emilk/eframe_template/pull/193
=> Revert "Update CI deployment"
